### ISSUE TITLE
0.5.4 does not build on Debian Jessie

### ISSUE THREAD

**Issue by tfoote** [moveit/geometric_shapes#84]
It is using a too new version of console bridge. This has caused the regression of ~71 downstream packages so I'm rolling it's release into kinetic back:https://github.com/ros/rosdistro/pull/17589

For example: http://build.ros.org/job/Kbin_dj_dJ64__geometric_shapes__debian_jessie_amd64__binary/53/console
```
00:23:11.534 make -f CMakeFiles/geometric_shapes.dir/build.make CMakeFiles/geometric_shapes.dir/depend
00:23:11.536 make[4]: Entering directory '/tmp/binarydeb/ros-kinetic-geometric-shapes-0.5.4/obj-x86_64-linux-gnu'
00:23:11.536 cd /tmp/binarydeb/ros-kinetic-geometric-shapes-0.5.4/obj-x86_64-linux-gnu && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/binarydeb/ros-kinetic-geometric-shapes-0.5.4 /tmp/binarydeb/ros-kinetic-geometric-shapes-0.5.4 /tmp/binarydeb/ros-kinetic-geometric-shapes-0.5.4/obj-x86_64-linux-gnu /tmp/binarydeb/ros-kinetic-geometric-shapes-0.5.4/obj-x86_64-linux-gnu /tmp/binarydeb/ros-kinetic-geometric-shapes-0.5.4/obj-x86_64-linux-gnu/CMakeFiles/geometric_shapes.dir/DependInfo.cmake --color=
00:23:11.615 Scanning dependencies of target geometric_shapes
00:23:11.616 make[4]: Leaving directory '/tmp/binarydeb/ros-kinetic-geometric-shapes-0.5.4/obj-x86_64-linux-gnu'
00:23:11.617 make -f CMakeFiles/geometric_shapes.dir/build.make CMakeFiles/geometric_shapes.dir/build
00:23:11.629 make[4]: Entering directory '/tmp/binarydeb/ros-kinetic-geometric-shapes-0.5.4/obj-x86_64-linux-gnu'
00:23:11.629 /usr/bin/cmake -E cmake_progress_report /tmp/binarydeb/ros-kinetic-geometric-shapes-0.5.4/obj-x86_64-linux-gnu/CMakeFiles 1
00:23:11.637 [ 14%] Building CXX object CMakeFiles/geometric_shapes.dir/src/bodies.cpp.o
00:23:11.646 /usr/lib/ccache/c++   -DGEOMETRIC_SHAPES_HAVE_QHULL_2011 -Dgeometric_shapes_EXPORTS -Dqh_QHpointer -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -DNDEBUG -D_FORTIFY_SOURCE=2  -fPIC -I/tmp/binarydeb/ros-kinetic-geometric-shapes-0.5.4/include -I/usr/include/eigen3 -I/usr/include/assimp -I/opt/ros/kinetic/include    -std=c++11 -o CMakeFiles/geometric_shapes.dir/src/bodies.cpp.o -c /tmp/binarydeb/ros-kinetic-geometric-shapes-0.5.4/src/bodies.cpp
00:23:15.908 /tmp/binarydeb/ros-kinetic-geometric-shapes-0.5.4/src/bodies.cpp: In member function ‘virtual void bodies::ConvexMesh::useDimensions(const shapes::Shape*)’:
00:23:15.908 /tmp/binarydeb/ros-kinetic-geometric-shapes-0.5.4/src/bodies.cpp:811:57: error: ‘CONSOLE_BRIDGE_logWarn’ was not declared in this scope
00:23:15.908      CONSOLE_BRIDGE_logWarn("Convex hull creation failed");
00:23:15.908                                                          ^
00:23:15.908 /tmp/binarydeb/ros-kinetic-geometric-shapes-0.5.4/src/bodies.cpp: In member function ‘void bodies::BodyVector::setPose(unsigned int, const Affine3d&)’:
00:23:15.908 /tmp/binarydeb/ros-kinetic-geometric-shapes-0.5.4/src/bodies.cpp:1209:62: error: ‘CONSOLE_BRIDGE_logError’ was not declared in this scope
00:23:15.908      CONSOLE_BRIDGE_logError("There is no body at index %u", i);
00:23:15.908                                                               ^
00:23:15.908 /tmp/binarydeb/ros-kinetic-geometric-shapes-0.5.4/src/bodies.cpp: In member function ‘const bodies::Body* bodies::BodyVector::getBody(unsigned int) const’:
00:23:15.908 /tmp/binarydeb/ros-kinetic-geometric-shapes-0.5.4/src/bodies.cpp:1220:62: error: ‘CONSOLE_BRIDGE_logError’ was not declared in this scope
00:23:15.908      CONSOLE_BRIDGE_logError("There is no body at index %u", i);
00:23:15.908                                                               ^
00:23:15.909 CMakeFiles/geometric_shapes.dir/build.make:57: recipe for target 'CMakeFiles/geometric_shapes.dir/src/bodies.cpp.o' failed
00:23:15.909 make[4]: *** [CMakeFiles/geometric_shapes.dir/src/bodies.cpp.o] Error 1
00:23:15.909 make[4]: Leaving directory '/tmp/binarydeb/ros-kinetic-geometric-shapes-0.5.4/obj-x86_64-linux-gnu'
00:23:15.909 CMakeFiles/Makefile2:156: recipe for target 'CMakeFiles/geometric_shapes.dir/all' failed
00:23:15.910 make[3]: *** [CMakeFiles/geometric_shapes.dir/all] Error 2
00:23:15.910 make[3]: Leaving directory '/tmp/binarydeb/ros-kinetic-geometric-shapes-0.5.4/obj-x86_64-linux-gnu'
00:23:15.910 Makefile:120: recipe for target 'all' failed
00:23:15.910 make[2]: *** [all] Error 2
00:23:15.910 make[2]: Leaving directory '/tmp/binarydeb/ros-kinetic-geometric-shapes-0.5.4/obj-x86_64-linux-gnu'
00:23:15.910 dh_auto_build: make -j1 returned exit code 2
00:23:15.912 debian/rules:35: recipe for target 'override_dh_auto_build' failed
00:23:15.912 make[1]: *** [override_dh_auto_build] Error 2
00:23:15.912 make[1]: Leaving directory '/tmp/binarydeb/ros-kinetic-geometric-shapes-0.5.4'
00:23:15.914 debian/rules:22: recipe for target 'build' failed
00:23:15.914 make: *** [build] Error 2
00:23:15.915 dpkg-buildpackage: error: debian/rules build gave error exit status 2
00:23:15.917 E: Building failed
00:23:15.920 Traceback (most recent call last):
00:23:15.921   File "/tmp/ros_buildfarm/ros_buildfarm/binarydeb_job.py", line 138, in build_binarydeb
00:23:15.921     subprocess.check_call(cmd, cwd=source_dir)
00:23:15.921   File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
00:23:15.921     raise CalledProcessError(retcode, cmd)
00:23:15.921 subprocess.CalledProcessError: Command '['apt-src', 'build', 'ros-kinetic-geometric-shapes']' returned non-zero exit status 1
00:23:15.921 
```

It is possible to support both versions of the console bridge API through a single source tree using macros like this: https://github.com/ros/class_loader/blob/indigo-devel/include/class_loader/console_bridge_compatibility.hpp however another common approach is to simply fork the development branches.

**Comment by rhaschke** [comment]
Thanks for pointing this out. I think, branching is not an option, as only a single branch (Kinetic) is already facing different versions of `console_bridge` in different OS systems. Hence, I filed PR #85 using the suggested compatibility layer.
